Currency/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Currency.ViewModels
{
    public class LoginViewModel
    {
        public int Id { get; set; }
        public string Login { get; set; }   
        public string Password { get; set; }
        public string retrunUrl { get; set; }
    }
}

Currency/ViewModels/SignUpViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Currency.ViewModels
{
    public class SignUpViewModel
    {
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    }
}

Currency/Controllers/SignController.cs
using Currency.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Currency.Controllers
{
    public class SignController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;

        private readonly SignInManager<IdentityUser> _signInManager;
        public SignController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }
        [HttpGet]
        public IActionResult Login(string ReturnUrl) => View(new LoginViewModel {retrunUrl = ReturnUrl });
        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var user = await _userManager.FindByNameAsync(model.Login);
            if (user == null)
            {
                ModelState.AddModelError("Login","Имя пользователя не найдено");
                return View(model);
            }
            var result = await _signInManager.PasswordSignInAsync(model.Login, model.Password, false, false);
            if (result.Succeeded)
                return Redirect(model.retrunUrl ?? "/home/Index");
            ModelState.AddModelError("Login", "Login or password is incorrect");
            return View(model);
        }
        [HttpGet]
        public IActionResult SignUp() => View();
        [HttpPost]
        public async Task<IActionResult> SignUp(SignUpViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var user = new IdentityUser
            {
                UserName = model.Login,
                Email = model.Email,
                PhoneNumber = model.PhoneNumber
            };
            var result = await _userManager.CreateAsync(user, model.Password);
            if (result.Succeeded)
            {
                await _userManager.AddToRoleAsync(user, "User");
                return RedirectToAction("Login");
            }
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(error.Code, error.Description);
            }
            return View(model);
        }
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Login");
        }
        
        


    }
}

Currency/Views/Sign/Login.cshtml
@model Currency.ViewModels.LoginViewModel
@{
    ViewData["Title"] = "Login";
}
<div class="row">
    <div class="text-danger" asp-validation-summary="All">
    </div>
    <div class="col-md-4"></div>
    <div class="col-md-4" style="margin-top:100px">
        <form class="form-group" action="Login" method="post">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Авторизация</h5>
                    <div class="form-group">
                        <label for="Login">Логин</label>
                        <input type="text" asp-for="Login" class="form-control" placeholder="Ваш логин">
                    </div>
                    <div class="form-group">
                        <label>Пароль</label>
                        <input type="password" asp-for="Password" class="form-control" id="exampleInputPassword1" placeholder="Ваш пароль">
                    </div>
                    <div class="form-check">
                        <input type="hidden" asp-for="retrunUrl" />
                    </div>
                    <button type="submit" class="btn btn-primary">Войти</button>
                    <a class="nav-link text-primary" asp-controller="Sign" asp-action="SignUp"> У вас ещё нет аккаунта? <strong>Зарегистрироваться</strong></a>
                </div>
            </div>
        </form>
    </div>
</div>

Currency/Views/Sign/SignUp.cshtml
@model Currency.ViewModels.SignUpViewModel
@{
    ViewData["Title"] = "SignUp";
}
<div class="row justify-content-center">
    <div asp-validation-summary="All"></div>
    <div class="col-md-6 p-3">
        <form action="SignUp" method="post">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Регистрация</h5>

                    <label>Контактные номера</label>
                    <input type="tel" asp-for="PhoneNumber" required class="form-control" />
                    <label>Email адрес</label>
                    <input type="email" asp-for="Email" required class="form-control" />
                    <label>Логин</label>
                    <input type="text" asp-for="Login" required class="form-control" />
                    <label>Пароль</label>
                    <input type="password" asp-for="Password" required class="form-control" />
                </div>
                <div class="card-footer">
                    <input type="submit" class="btn btn-outline-primary btn-block" value="Зарегистрироваться" />
                </div>
            </div>
        </form>
    </div>
</div>